[project]
name="plover_melani_es"
version="0.0.0"
authors = [
    {name="Raúl E. Taveras", email="raul@raultaveras.online" }
]
description = "Simple implementation of the Melani system for Spanish stenography according to public information."
readme = "README.md"

[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"
