[metadata]
name = plover-melani-es
keywords = plover plover_plugin spanish

[options]
zip_safe = True
setup_requires =
  setuptools>=79.0.0 # just an example, might need to be higher
install_requires =
  plover>=4.0.0.dev10 # or higher, especially for GUI plugins
packages =
  plover_melani_es

[options.entry_points]
plover.system =
    Melani Spanish = plover_melani_es.system
